# Generated by Django 5.0 on 2024-03-11 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_rename_cart_carts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('tx_ref', models.CharField(max_length=100)),
                ('transaction_id', models.CharField(max_length=100)),
            ],
        ),
    ]
