# Generated by Django 5.0 on 2024-03-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='customer_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
