# Generated by Django 5.0 on 2025-01-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_rename_total_amount_order_total_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
